# Generated by Django 5.0.6 on 2024-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=9999999999999)),
                ('Content', models.CharField(max_length=9999999999999)),
            ],
        ),
        migrations.CreateModel(
            name='UserRansom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=9999999999999)),
                ('AboutUser', models.CharField(blank=True, default=False, max_length=4000)),
                ('Published', models.BooleanField(blank=True, default=False)),
                ('Files', models.ManyToManyField(blank=True, to='web.file')),
            ],
        ),
    ]
