# Generated by Django 5.0.6 on 2024-05-08 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userransom_certslocation_alter_file_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userransom',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
