# Generated by Django 5.0.6 on 2024-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_userransom_certspassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userransom',
            name='AboutUser',
        ),
        migrations.AlterField(
            model_name='userransom',
            name='CertsLocation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userransom',
            name='CertsPassword',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userransom',
            name='Published',
            field=models.BooleanField(default=False),
        ),
    ]
