# Generated by Django 5.0.6 on 2024-05-09 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_userransom_aboutuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='UploadedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
